dist: trusty
language: node_js
node_js:
  - "14"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  # yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  # Repo for Yarn
  # - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  # - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  # - sudo apt-get update -qq
  # - sudo apt-get install -y -qq yarn=1.22.5-1
  # Other
  - sh -e /etc/init.d/xvfb start
cache:
  yarn: true
install:
  - yarn
script:
  - yarn install
  - yarn run lint
  - yarn run test -- --watch=false
  # - yarn run pree2e
  # - yarn run e2e
# cache: yarn