dist: trusty
sudo: required
language: node_js
node_js:
  - "16"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
  # - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.10
  # - export PATH="$HOME/.yarn/bin:$PATH"
# install:
#   - yarn
script:
  - npm install yarn
  - yarn install
  - yarn run lint
  - yarn run test -- --watch=false
  # - yarn run pree2e
  # - yarn run e2e
# cache: yarn